### ISSUE TITLE
Optimiser fails to send request to reconfigure resources

### ISSUE THREAD

**Issue by jmarchel7bulls** [eu-nebulous/optimiser-controller#32]
In logs we could witness the request from the solver to re-deploy the app:

[INFO ] 2024-10-14 20:18:19.792 [pool-2-thread-2] NebulOuSMessageBrokerListener - 
eu.nebulouscloud.optimiser.solver.solution
subject:null
properties:{application=b59418e6-6dc3-4389-b6da-fd901b0bd7fc}
correlationId:null
payload:{"VariableValues":{"spec_components_5_properties_memory":8.0,"spec_components_5_properties_cpu":8.0,"cost_pi_spec_components_5":0.42481996272447387},"ObjectiveValues":{"costfunction":0.42481996272447387,"SimpleUf":24.0},"ObjectiveFunction":"SimpleUf","Timestamp":1728929894478,"DeploySolution":true}

and then NullPointerException was seen in the Optimiser:
{"@timestamp":"2024-10-14T18:18:18.017637555Z","@version":"1","message":"Processing message fortopic://eu.nebulouscloud.optimiser.solver.solution","logger_name":"eu.nebulouscloud.exn.core.Consumer","thread_name":"pool-12-thread-7","level":"DEBUG","level_value":10000}
{"@timestamp":"2024-10-14T18:18:18.018204787Z","@version":"1","message":"Sending solver solution to application for redeployment","logger_name":"eu.nebulouscloud.optimiser.controller.ExnConnector","thread_name":"pool-12-thread-7","level":"DEBUG","level_value":10000,"appId":"b59418e6-6dc3-4389-b6da-fd901b0bd7fc","clusterName":"b5941-3"}
{"@timestamp":"2024-10-14T18:18:18.018603692Z","@version":"1","message":"Received solver solution for application","logger_name":"eu.nebulouscloud.optimiser.controller.ExnConnector","thread_name":"Thread-4","level":"DEBUG","level_value":10000,"appId":"b59418e6-6dc3-4389-b6da-fd901b0bd7fc","clusterName":"b5941-3"}
Exception in thread "Thread-4" java.lang.NullPointerException
{"@timestamp":"2024-10-14T18:18:27.575070435Z","@version":"1","message":"Processing scheduled executor [health] topic://eu.nebulouscloud.optimiser_controller.health  ","logger_name":"eu.nebulouscloud.exn.core.Manager","thread_name":"pool-12-thread-8","level":"DEBUG","level_value":10000}

**Comment by rudi** [comment]
Any chance to get the contents of the solver solution message, or full logs with a backtrace of the error?  Otherwise this is really hard to diagnose.

**Comment by rudi** [comment]
I'm adding a fix for when the DeploySolution field is entirely missing instead of being true or false; this is the only source of a null-pointer exception between the log that's printed and the next log that's missing that I can see.  Hopefully this fixes the issue.
