### ISSUE TITLE
When filtering node candidate by region, ignore regions field when "null"

### ISSUE THREAD

**Issue by robert-sanfeliu** [eu-nebulous/optimiser-controller#56]
If "regions" value is **"null"**, it should be ignored. Example:
{"title":"eut-aws-good","uuid":"c9a625c7-f705-4128-948f-6b5765509029","platform":"AWS","enabled":false,"regions":"null"}

This should be done extending https://github.com/eu-nebulous/optimiser-controller/issues/36

**Comment by rudi** [comment]
Could you clarify if you mean `"regions":"null"` (as in the example) or `"regions":null` (as in the bug title)?  Or both?  (Should we be able to handle a cloud provider that has a region named "null"?)

**Comment by rudi** [comment]
Clarified via chat that indeed we have to filter out regions called `"null"`.
