### ISSUE TITLE
Add default values for variables in the AMPL file

### ISSUE THREAD

**Issue by GeirHo** [eu-nebulous/optimiser-controller#7]
Extend the AMPL file generator to include the default value at the minimum border of the variable domain. Thus if a variable is defined as 

var NoInstances >=2 <=15

The default value of two should be given at the end of the statement, so the correct statement should be:

var NoInstances >=2 <= 15 := 2

as this also confirms to the initial configuration deployed by the Optimizer.

**Comment by rudi** [comment]
Small question about the syntax.  The above examples say `var NoInstances >=2 <=15` but the code currently generates `var NoInstances >=2, <=15`.  Can you confirm that the code that should be generated is `var NoInstances >=2, <=15 := 2` ?
